<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
//Add
use App\Models\Settings\Organization;

class OrganizationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Default
        $items = [
            //Counties
            ["category_id"=>1, "name"=>"County Government of Mombasa"],
            ["category_id"=>1, "name"=>"County Government of Kwale"],
            ["category_id"=>1, "name"=>"County Government of Kilifi"],
            ["category_id"=>1, "name"=>"County Government of Tana River"],
            ["category_id"=>1, "name"=>"County Government of Lamu"],
            ["category_id"=>1, "name"=>"County Government of Taita Taveta"],
            ["category_id"=>1, "name"=>"County Government of Garissa"],
            ["category_id"=>1, "name"=>"County Government of Wajir"],
            ["category_id"=>1, "name"=>"County Government of Mandera" ],
            ["category_id"=>1, "name"=>"County Government of Marsabit"],
            ["category_id"=>1, "name"=>"County Government of Isiolo"],
            ["category_id"=>1, "name"=>"County Government of Meru"],
            ["category_id"=>1, "name"=>"County Government of Tharaka Nithi"],
            ["category_id"=>1, "name"=>"County Government of Embu"],
            ["category_id"=>1, "name"=>"County Government of Kitui"],
            ["category_id"=>1, "name"=>"County Government of Machakos"],
            ["category_id"=>1, "name"=>"County Government of Makueni"],
            ["category_id"=>1, "name"=>"County Government of Nyandarua"],
            ["category_id"=>1, "name"=>"County Government of Nyeri"],
            ["category_id"=>1, "name"=>"County Government of Kirinyaga"],
            ["category_id"=>1, "name"=>"County Government of Muranga"],
            ["category_id"=>1, "name"=>"County Government of Kiambu"],
            ["category_id"=>1, "name"=>"County Government of Turkana"],
            ["category_id"=>1, "name"=>"County Government of West Pokot"],
            ["category_id"=>1, "name"=>"County Government of Samburu"],
            ["category_id"=>1, "name"=>"County Government of Trans Nzoia"],
            ["category_id"=>1, "name"=>"County Government of Uasin Gishu"],
            ["category_id"=>1, "name"=>"County Government of Elgeyo Marakwet"],
            ["category_id"=>1, "name"=>"County Government of Nandi"],
            ["category_id"=>1, "name"=>"County Government of Baringo"],
            ["category_id"=>1, "name"=>"County Government of Laikipia"],
            ["category_id"=>1, "name"=>"County Government of Nakuru"],
            ["category_id"=>1, "name"=>"County Government of Narok"],
            ["category_id"=>1, "name"=>"County Government of Kajiado"],
            ["category_id"=>1, "name"=>"County Government of Kericho"],
            ["category_id"=>1, "name"=>"County Government of Bomet"],
            ["category_id"=>1, "name"=>"County Government of Kakamega"],
            ["category_id"=>1, "name"=>"County Government of Vihiga"],
            ["category_id"=>1, "name"=>"County Government of Bungoma"],
            ["category_id"=>1, "name"=>"County Government of Busia"],
            ["category_id"=>1, "name"=>"County Government of Siaya"],
            ["category_id"=>1, "name"=>"County Government of Kisumu"],
            ["category_id"=>1, "name"=>"County Government of Homa Bay"],
            ["category_id"=>1, "name"=>"County Government of Migori"],
            ["category_id"=>1, "name"=>"County Government of Kisii"],
            ["category_id"=>1, "name"=>"County Government of Nyamira"],
            ["category_id"=>1, "name"=>"County Government of Nairobi"],

            //Ministries
            ["category_id"=>2, "name"=>"Ministry of Interior and Coordination of National Government"],
            ["category_id"=>2, "name"=>"Ministry of Finance and treasury"],
            ["category_id"=>2, "name"=>"Ministry of Defence"],
            ["category_id"=>2, "name"=>"Ministry of Health"],
            ["category_id"=>2, "name"=>"Ministry of Ministry of Education, Science and Technology"],
            ["category_id"=>2, "name"=>"Ministry of Transport and Infrastructure Development"],
            ["category_id"=>2, "name"=>"Ministry of Devolution and Arid and Semi-Arid Lands (ASALs)"],
            ["category_id"=>2, "name"=>"Ministry of Lands"],
            ["category_id"=>2, "name"=>"Ministry of Environment and Forestry"],
            ["category_id"=>2, "name"=>"Ministry of Mining and Petroleum"],
            ["category_id"=>2, "name"=>"Ministry of Agriculture and Irrigation"],
            ["category_id"=>2, "name"=>"Ministry of East African Community and Northern Corridor Development"],
            ["category_id"=>2, "name"=>"Labour and Social Protection"],
            ["category_id"=>2, "name"=>"Ministry of Tourism and Wildlife"],
            ["category_id"=>2, "name"=>"Ministry of Water and Sanitation"],
            ["category_id"=>2, "name"=>"Ministry of Energy"],
            ["category_id"=>2, "name"=>"Industrialisation and Enterprise Development"],
            ["category_id"=>2, "name"=>"Public Service, Youth and Gender Affairs"],
            ["category_id"=>2, "name"=>"Ministry of Information, Communication and Technology"],
            ["category_id"=>2, "name"=>"Ministry of Sports and Heritage"],

            //State Departments
            ["category_id"=>3, "name"=>"Office of the President"],
            ["category_id"=>3, "name"=>"Office of the Deputy President"],
            ["category_id"=>3, "name"=>"Cabinet Affairs Office"],
            ["category_id"=>3, "name"=>"State Department of Interior "],
            ["category_id"=>3, "name"=>"State Department of Correctional and Rehabilitation Services"],
            ["category_id"=>3, "name"=>"State Department of Immigration, Border Control and Registration of Persons"],
            ["category_id"=>3, "name"=>"The National Treasury"],
            ["category_id"=>3, "name"=>"State Department for Planning"],
            ["category_id"=>3, "name"=>"State Department of Foreign Affairs "],
            ["category_id"=>3, "name"=>"State Department of International Trade"],
            ["category_id"=>3, "name"=>"State Department of Defence"],
            ["category_id"=>3, "name"=>"State Department of Health"],
            ["category_id"=>3, "name"=>"State Department of Early Learning and Basic Education "],
            ["category_id"=>3, "name"=>"State Department of Post Training and Skills Development "],
            ["category_id"=>3, "name"=>"State Department of University Education and Research"],
            ["category_id"=>3, "name"=>"State Department of Transport "],
            ["category_id"=>3, "name"=>"State Department of Infrastructure "],
            ["category_id"=>3, "name"=>"State Department of Public Works"],
            ["category_id"=>3, "name"=>"State Department of Housing and Urban Development "],
            ["category_id"=>3, "name"=>"State Department of Shipping and Maritime Affairs"],
            ["category_id"=>3, "name"=>"State Department of Devolution"],
            ["category_id"=>3, "name"=>"State Department of Arid and Semi-Arid Lands (ASALs)"],
            ["category_id"=>3, "name"=>"State Department of Lands"],
            ["category_id"=>3, "name"=>"State Department of Environment and Forestry"],
            ["category_id"=>3, "name"=>"State Department of mining"],
            ["category_id"=>3, "name"=>"State Department of Petroleum"],
            ["category_id"=>3, "name"=>"State Department of Agricultural Research"],
            ["category_id"=>3, "name"=>"State Department of Crop Development "],
            ["category_id"=>3, "name"=>"State Department of Livestock "],
            ["category_id"=>3, "name"=>"State Department of Fisheries "],
            ["category_id"=>3, "name"=>"State Department of Irrigation"],
            ["category_id"=>3, "name"=>"State Department of East African Community and Northern Corridor Development"],
            ["category_id"=>3, "name"=>"State Department of Labour"],
            ["category_id"=>3, "name"=>"State Department of Social Protection, Pensions and Senior Citizens Affairs"],
            ["category_id"=>3, "name"=>"State Department of Tourism and Wildlife"],
            ["category_id"=>3, "name"=>"State Department of Water and Sanitation"],
            ["category_id"=>3, "name"=>"State Department of Public Service and Youth "],
            ["category_id"=>3, "name"=>"State Department of Gender Affairs"],
            ["category_id"=>3, "name"=>"State Department of Energy"],
            ["category_id"=>3, "name"=>"State Department of Renewable Energy"],
            ["category_id"=>3, "name"=>"State Department of Industrialisation"],
            ["category_id"=>3, "name"=>"State Department of Enterprise Development"],
            ["category_id"=>3, "name"=>"State Department of Information, Communication and Technology"],
            ["category_id"=>3, "name"=>"State Department of Sports"],
            ["category_id"=>3, "name"=>"State Department of Heritage"],


            //Gvt Agencies
            ["category_id"=>4, "name"=>"Kenya Airports Authority"],
            ["category_id"=>4, "name"=>"Attorney General of Kenya"],
            ["category_id"=>4, "name"=>"Central Bank of Kenya"],
            ["category_id"=>4, "name"=>"Capital Markets Authority of Kenya"],
            ["category_id"=>4, "name"=>"Kenya Civil Aviation Authority"],
            ["category_id"=>4, "name"=>"Betting Control and Licensing Board"],
            ["category_id"=>4, "name"=>"Insurance Regulatory Authority (Kenya)"],
            ["category_id"=>4, "name"=>"Retirement Benefits Authority of Kenya"],
            ["category_id"=>4, "name"=>"Sacco Societies Regulatory Authority"],
            ["category_id"=>4, "name"=>"Commission for the Implementation of the Constitution"],
            ["category_id"=>4, "name"=>"Commission on Administrative Justice"],
            ["category_id"=>4, "name"=>"Commission on Revenue Allocation"],
            ["category_id"=>4, "name"=>"Commissions and Independent Offices of Kenya"],
            ["category_id"=>4, "name"=>"Communications Authority of Kenya"],
            ["category_id"=>4, "name"=>"Kenya National Disaster Operation Centre"],
            ["category_id"=>4, "name"=>"Kenya Economic Stimulus Program"],
            ["category_id"=>4, "name"=>"Medical Practitioners and Dentists Board"],
            ["category_id"=>4, "name"=>"National Environment Management Authority of Kenya"],
            ["category_id"=>4, "name"=>"Ethics and Anti-Corruption Commission"],
            ["category_id"=>4, "name"=>"Export Promotion Council"],
            ["category_id"=>4, "name"=>"Kenya Film Classification Board"],
            ["category_id"=>4, "name"=>"Kenya Film Commission"],
            ["category_id"=>4, "name"=>"Clinical Officers Council"],
            ["category_id"=>4, "name"=>"Kenya Forest Service"],
            ["category_id"=>4, "name"=>"Kenya National Commission on Human Rights"],
            ["category_id"=>4, "name"=>"Information and Communication Technology Authority (Kenya)"],
            ["category_id"=>4, "name"=>"Judicial Service Commission (Kenya)"],
            ["category_id"=>4, "name"=>"Kenya Anti-Corruption Authority"],
            ["category_id"=>4, "name"=>"Kenya Anti-Corruption Commission"],
            ["category_id"=>4, "name"=>"Kenya Bureau of Standards"],
            ["category_id"=>4, "name"=>"Kenya Coast Guard Service"],
            ["category_id"=>4, "name"=>"Kenya National Examinations Council"],
            ["category_id"=>4, "name"=>"Kenya National Bureau of Statistics"],
            ["category_id"=>4, "name"=>"Kenya Medical Supplies Agency"],
            ["category_id"=>4, "name"=>"Kenya Law Reform Commission"],
            ["category_id"=>4, "name"=>"Kenya Judges and Magistrates Vetting Board"],
            ["category_id"=>4, "name"=>"National Intelligence Service (Kenya)"],
            ["category_id"=>4, "name"=>"National Hospital Insurance Fund"],
            ["category_id"=>4, "name"=>"National Cohesion and Integration Commission"],
            ["category_id"=>4, "name"=>"Kenya Defence Forces"],
            ["category_id"=>4, "name"=>"Kenya Army"],
            ["category_id"=>4, "name"=>"Kenya Plant Health Inspectorate Services"],
            ["category_id"=>4, "name"=>"Local authorities of Kenya"],
            ["category_id"=>4, "name"=>"Office of the Controller of Budget (Kenya)"],
            ["category_id"=>4, "name"=>"Office of the Auditor-General (Kenya)"],
            ["category_id"=>4, "name"=>"Kenya Navy"],
            ["category_id"=>4, "name"=>"National Youth Service (Kenya)"],
            ["category_id"=>4, "name"=>"National Social Security Fund (Kenya)"],
            ["category_id"=>4, "name"=>"National Police Service Commission"],
            ["category_id"=>4, "name"=>"National Land Commission"],
            ["category_id"=>4, "name"=>"Kenya Ports Authority"],
            ["category_id"=>4, "name"=>"Permanent Presidential Music Commission"],
            ["category_id"=>4, "name"=>"Permanent Presidential Commission on Soil Conservation and Afforestation"],
            ["category_id"=>4, "name"=>"Parliamentary Service Commission"],
            ["category_id"=>4, "name"=>"Teachers Service Commission"],
            ["category_id"=>4, "name"=>"Salaries and Remuneration Commission"],
            ["category_id"=>4, "name"=>"Kenya Revenue Authority"],
            ["category_id"=>4, "name"=>"Registrar of Trade Unions"],
            ["category_id"=>4, "name"=>"Public Service Commission (Kenya)"],
            ["category_id"=>4, "name"=>"Waki Commission"],
            ["category_id"=>4, "name"=>"Kenya Wildlife Service"],

            //Private Companies
            ["category_id"=>5, "name"=>"Safaricom"],
            ["category_id"=>5, "name"=>"Centum"],
            ["category_id"=>5, "name"=>"Google Kenya"],
            ["category_id"=>5, "name"=>"Pricewater Coopers (PwC)"],
            ["category_id"=>5, "name"=>"British American Tobacco (BAT)"],
            ["category_id"=>5, "name"=>"KPMG East Africa"],
            ["category_id"=>5, "name"=>"East African Breweries Limited (EABL)"],
            ["category_id"=>5, "name"=>"Royal Media Services"],
            ["category_id"=>5, "name"=>"IBM"],
            ["category_id"=>5, "name"=>"Deloitte"],
            ["category_id"=>5, "name"=>"Coca-cola"],
            ["category_id"=>5, "name"=>"Airtel Kenya"],
            ["category_id"=>5, "name"=>"Cytonn Investment"],
            ["category_id"=>5, "name"=>"Nation Media Group"],
            ["category_id"=>5, "name"=>"Toyota Kenya"],
            ["category_id"=>5, "name"=>"Bamburi Cement"],
            ["category_id"=>5, "name"=>"Unilever"],
            ["category_id"=>5, "name"=>"Nestle Kenya"],
        ];

        Organization::insert($items);
    }
}
